# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 567)
        MainWindow.setAccessibleName("")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout.setHorizontalSpacing(22)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.source_picker = QtWidgets.QComboBox(self.groupBox_3)
        self.source_picker.setObjectName("source_picker")
        self.source_picker.addItem("")
        self.source_picker.addItem("")
        self.source_picker.addItem("")
        self.source_picker.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.source_picker)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.pick_file_button = QtWidgets.QToolButton(self.groupBox_3)
        self.pick_file_button.setObjectName("pick_file_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pick_file_button)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setHorizontalSpacing(22)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.amplitude_slider = QtWidgets.QSlider(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amplitude_slider.sizePolicy().hasHeightForWidth())
        self.amplitude_slider.setSizePolicy(sizePolicy)
        self.amplitude_slider.setOrientation(QtCore.Qt.Horizontal)
        self.amplitude_slider.setObjectName("amplitude_slider")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.amplitude_slider)
        self.amplitude_label = QtWidgets.QLabel(self.groupBox)
        self.amplitude_label.setObjectName("amplitude_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.amplitude_label)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.radio_keep = QtWidgets.QRadioButton(self.groupBox)
        self.radio_keep.setObjectName("radio_keep")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.radio_keep)
        self.radio_remove = QtWidgets.QRadioButton(self.groupBox)
        self.radio_remove.setObjectName("radio_remove")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.radio_remove)
        self.keep_frequenties = QtWidgets.QLineEdit(self.groupBox)
        self.keep_frequenties.setObjectName("keep_frequenties")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.keep_frequenties)
        self.remove_frequencies = QtWidgets.QLineEdit(self.groupBox)
        self.remove_frequencies.setObjectName("remove_frequencies")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.remove_frequencies)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.domain_picker = QtWidgets.QComboBox(self.groupBox)
        self.domain_picker.setObjectName("domain_picker")
        self.domain_picker.addItem("")
        self.domain_picker.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.domain_picker)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_3.setHorizontalSpacing(22)
        self.formLayout_3.setVerticalSpacing(15)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.output_target = QtWidgets.QComboBox(self.groupBox_2)
        self.output_target.setObjectName("output_target")
        self.output_target.addItem("")
        self.output_target.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.output_target)
        self.write_button = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_button.sizePolicy().hasHeightForWidth())
        self.write_button.setSizePolicy(sizePolicy)
        self.write_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.write_button.setFlat(False)
        self.write_button.setObjectName("write_button")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.write_button)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.plot_view = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_view.sizePolicy().hasHeightForWidth())
        self.plot_view.setSizePolicy(sizePolicy)
        self.plot_view.setObjectName("plot_view")
        self.horizontalLayout.addWidget(self.plot_view)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Physics Experiments Data Analysis"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Input"))
        self.label_3.setText(_translate("MainWindow", "Source"))
        self.source_picker.setItemText(0, _translate("MainWindow", "File"))
        self.source_picker.setItemText(1, _translate("MainWindow", "Sine"))
        self.source_picker.setItemText(2, _translate("MainWindow", "MyDaq device"))
        self.source_picker.setItemText(3, _translate("MainWindow", "Rigol Oscilloscope"))
        self.label_4.setText(_translate("MainWindow", "Pick file"))
        self.pick_file_button.setText(_translate("MainWindow", "..."))
        self.groupBox.setTitle(_translate("MainWindow", "Filter"))
        self.label_2.setText(_translate("MainWindow", "Amplitude filter"))
        self.amplitude_label.setText(_translate("MainWindow", "50 (min: 30, max: 50)"))
        self.label_8.setText(_translate("MainWindow", "Frequency filter"))
        self.radio_keep.setText(_translate("MainWindow", "Keep only:"))
        self.radio_remove.setText(_translate("MainWindow", "Remove only:"))
        self.label_5.setText(_translate("MainWindow", "Show"))
        self.domain_picker.setItemText(0, _translate("MainWindow", "Frequency Domain"))
        self.domain_picker.setItemText(1, _translate("MainWindow", "Time Domain"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Output"))
        self.label_9.setText(_translate("MainWindow", "Target"))
        self.output_target.setItemText(0, _translate("MainWindow", "File"))
        self.output_target.setItemText(1, _translate("MainWindow", "MyDaq device"))
        self.write_button.setText(_translate("MainWindow", "Write"))
        self.label.setText(_translate("MainWindow", "© Tobias Göbel & Léon van Velzen"))

from pyqtgraph import PlotWidget
