# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 703)
        MainWindow.setAccessibleName("")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setObjectName("tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setContentsMargins(9, -1, 9, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.source_picker = QtWidgets.QComboBox(self.frame_4)
        self.source_picker.setObjectName("source_picker")
        self.source_picker.addItem("")
        self.source_picker.addItem("")
        self.source_picker.addItem("")
        self.source_picker.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.source_picker)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.controls_stack = QtWidgets.QStackedWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controls_stack.sizePolicy().hasHeightForWidth())
        self.controls_stack.setSizePolicy(sizePolicy)
        self.controls_stack.setObjectName("controls_stack")
        self.sine_controls = QtWidgets.QWidget()
        self.sine_controls.setObjectName("sine_controls")
        self.formLayout_4 = QtWidgets.QFormLayout(self.sine_controls)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_2 = QtWidgets.QLabel(self.sine_controls)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.amplitude_edit = QtWidgets.QLineEdit(self.sine_controls)
        self.amplitude_edit.setObjectName("amplitude_edit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.amplitude_edit)
        self.label_7 = QtWidgets.QLabel(self.sine_controls)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.endtime_edit = QtWidgets.QLineEdit(self.sine_controls)
        self.endtime_edit.setObjectName("endtime_edit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.endtime_edit)
        self.label_6 = QtWidgets.QLabel(self.sine_controls)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.frequency_edit = QtWidgets.QLineEdit(self.sine_controls)
        self.frequency_edit.setObjectName("frequency_edit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.frequency_edit)
        self.label_8 = QtWidgets.QLabel(self.sine_controls)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.mean_edit = QtWidgets.QLineEdit(self.sine_controls)
        self.mean_edit.setObjectName("mean_edit")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.mean_edit)
        self.label_10 = QtWidgets.QLabel(self.sine_controls)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.deviation_edit = QtWidgets.QLineEdit(self.sine_controls)
        self.deviation_edit.setObjectName("deviation_edit")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.deviation_edit)
        self.controls_stack.addWidget(self.sine_controls)
        self.file_controls = QtWidgets.QWidget()
        self.file_controls.setObjectName("file_controls")
        self.formLayout_5 = QtWidgets.QFormLayout(self.file_controls)
        self.formLayout_5.setObjectName("formLayout_5")
        self.sample_time_edit = QtWidgets.QLineEdit(self.file_controls)
        self.sample_time_edit.setInputMask("")
        self.sample_time_edit.setText("")
        self.sample_time_edit.setObjectName("sample_time_edit")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sample_time_edit)
        self.label_11 = QtWidgets.QLabel(self.file_controls)
        self.label_11.setObjectName("label_11")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_4 = QtWidgets.QLabel(self.file_controls)
        self.label_4.setObjectName("label_4")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.pick_file_button = QtWidgets.QToolButton(self.file_controls)
        self.pick_file_button.setObjectName("pick_file_button")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pick_file_button)
        self.controls_stack.addWidget(self.file_controls)
        self.delta_controls = QtWidgets.QWidget()
        self.delta_controls.setObjectName("delta_controls")
        self.formLayout_3 = QtWidgets.QFormLayout(self.delta_controls)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.delta_controls)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.delta_amplitude = QtWidgets.QLineEdit(self.delta_controls)
        self.delta_amplitude.setObjectName("delta_amplitude")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.delta_amplitude)
        self.label_12 = QtWidgets.QLabel(self.delta_controls)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.delta_end_time = QtWidgets.QLineEdit(self.delta_controls)
        self.delta_end_time.setObjectName("delta_end_time")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.delta_end_time)
        self.controls_stack.addWidget(self.delta_controls)
        self.gauss_controls = QtWidgets.QWidget()
        self.gauss_controls.setObjectName("gauss_controls")
        self.formLayout = QtWidgets.QFormLayout(self.gauss_controls)
        self.formLayout.setObjectName("formLayout")
        self.label_17 = QtWidgets.QLabel(self.gauss_controls)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.gauss_amplitude = QtWidgets.QLineEdit(self.gauss_controls)
        self.gauss_amplitude.setObjectName("gauss_amplitude")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gauss_amplitude)
        self.label_18 = QtWidgets.QLabel(self.gauss_controls)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.gauss_sigma = QtWidgets.QLineEdit(self.gauss_controls)
        self.gauss_sigma.setObjectName("gauss_sigma")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gauss_sigma)
        self.gauss_end_time = QtWidgets.QLineEdit(self.gauss_controls)
        self.gauss_end_time.setObjectName("gauss_end_time")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gauss_end_time)
        self.label_19 = QtWidgets.QLabel(self.gauss_controls)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.controls_stack.addWidget(self.gauss_controls)
        self.verticalLayout_3.addWidget(self.controls_stack)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.write_button = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_button.sizePolicy().hasHeightForWidth())
        self.write_button.setSizePolicy(sizePolicy)
        self.write_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.write_button.setFlat(False)
        self.write_button.setObjectName("write_button")
        self.verticalLayout_5.addWidget(self.write_button)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widget)
        self.frame = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.generated_time_plot = PlotWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generated_time_plot.sizePolicy().hasHeightForWidth())
        self.generated_time_plot.setSizePolicy(sizePolicy)
        self.generated_time_plot.setObjectName("generated_time_plot")
        self.verticalLayout_2.addWidget(self.generated_time_plot)
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.generated_frequency_plot = PlotWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generated_frequency_plot.sizePolicy().hasHeightForWidth())
        self.generated_frequency_plot.setSizePolicy(sizePolicy)
        self.generated_frequency_plot.setObjectName("generated_frequency_plot")
        self.verticalLayout_2.addWidget(self.generated_frequency_plot)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.incoming_time_plot = PlotWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.incoming_time_plot.sizePolicy().hasHeightForWidth())
        self.incoming_time_plot.setSizePolicy(sizePolicy)
        self.incoming_time_plot.setObjectName("incoming_time_plot")
        self.verticalLayout_6.addWidget(self.incoming_time_plot)
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_6.addWidget(self.label_16)
        self.incoming_frequency_plot = PlotWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.incoming_frequency_plot.sizePolicy().hasHeightForWidth())
        self.incoming_frequency_plot.setSizePolicy(sizePolicy)
        self.incoming_frequency_plot.setObjectName("incoming_frequency_plot")
        self.verticalLayout_6.addWidget(self.incoming_frequency_plot)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)
        self.tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox = QtWidgets.QGroupBox(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.bode_progress = QtWidgets.QProgressBar(self.groupBox)
        self.bode_progress.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bode_progress.sizePolicy().hasHeightForWidth())
        self.bode_progress.setSizePolicy(sizePolicy)
        self.bode_progress.setProperty("value", 24)
        self.bode_progress.setObjectName("bode_progress")
        self.gridLayout.addWidget(self.bode_progress, 6, 0, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 0, 0, 1, 1)
        self.frequency_start_edit = QtWidgets.QLineEdit(self.groupBox)
        self.frequency_start_edit.setObjectName("frequency_start_edit")
        self.gridLayout.addWidget(self.frequency_start_edit, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 1, 0, 1, 1)
        self.frequency_end_edit = QtWidgets.QLineEdit(self.groupBox)
        self.frequency_end_edit.setObjectName("frequency_end_edit")
        self.gridLayout.addWidget(self.frequency_end_edit, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 0, 1, 1)
        self.bode_plot_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bode_plot_button.sizePolicy().hasHeightForWidth())
        self.bode_plot_button.setSizePolicy(sizePolicy)
        self.bode_plot_button.setObjectName("bode_plot_button")
        self.gridLayout.addWidget(self.bode_plot_button, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox)
        self.horizontalLayout_5.addWidget(self.widget_5)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.amplitude_plot = PlotWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amplitude_plot.sizePolicy().hasHeightForWidth())
        self.amplitude_plot.setSizePolicy(sizePolicy)
        self.amplitude_plot.setObjectName("amplitude_plot")
        self.verticalLayout_8.addWidget(self.amplitude_plot)
        self.horizontalLayout_5.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_20 = QtWidgets.QLabel(self.widget_4)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_9.addWidget(self.label_20)
        self.phase_plot = PlotWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phase_plot.sizePolicy().hasHeightForWidth())
        self.phase_plot.setSizePolicy(sizePolicy)
        self.phase_plot.setObjectName("phase_plot")
        self.verticalLayout_9.addWidget(self.phase_plot)
        self.horizontalLayout_5.addWidget(self.widget_4)
        self.verticalLayout_7.addWidget(self.widget_2)
        self.tabs.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.tabs)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(1)
        self.controls_stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Physics Experiments Data Analysis"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Input"))
        self.label_3.setText(_translate("MainWindow", "Source"))
        self.source_picker.setItemText(0, _translate("MainWindow", "File"))
        self.source_picker.setItemText(1, _translate("MainWindow", "Sine"))
        self.source_picker.setItemText(2, _translate("MainWindow", "Gauss"))
        self.source_picker.setItemText(3, _translate("MainWindow", "Delta"))
        self.label_2.setText(_translate("MainWindow", "Amplitude (V)"))
        self.amplitude_edit.setText(_translate("MainWindow", "1"))
        self.label_7.setText(_translate("MainWindow", "Eindtijd (s)"))
        self.endtime_edit.setText(_translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "Frequency (Hz)"))
        self.frequency_edit.setText(_translate("MainWindow", "1"))
        self.label_8.setText(_translate("MainWindow", "Mean Noise"))
        self.mean_edit.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "Deviation Noise"))
        self.deviation_edit.setText(_translate("MainWindow", "0.1"))
        self.label_11.setText(_translate("MainWindow", "Sample Time (s)"))
        self.label_4.setText(_translate("MainWindow", "Pick file"))
        self.pick_file_button.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "Amplitude (V)"))
        self.label_12.setText(_translate("MainWindow", "End Time (s)"))
        self.label_17.setText(_translate("MainWindow", "Amplitude (V)"))
        self.label_18.setText(_translate("MainWindow", "Sigma"))
        self.label_19.setText(_translate("MainWindow", "End time (s)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Output"))
        self.write_button.setText(_translate("MainWindow", "Write Data"))
        self.label_14.setText(_translate("MainWindow", "Generated Signal Time Domain"))
        self.label_15.setText(_translate("MainWindow", "Generated Signal Frequency Domain"))
        self.label_13.setText(_translate("MainWindow", "Incoming Signal Time Domain"))
        self.label_16.setText(_translate("MainWindow", "Incoming Signal Frequency Domain"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("MainWindow", "PE1, Practicum 3"))
        self.groupBox.setTitle(_translate("MainWindow", "Settings"))
        self.label_21.setText(_translate("MainWindow", "Frequency start (Hz)"))
        self.frequency_start_edit.setText(_translate("MainWindow", "5"))
        self.label_22.setText(_translate("MainWindow", "Frequency end (Hz)"))
        self.frequency_end_edit.setText(_translate("MainWindow", "150"))
        self.bode_plot_button.setText(_translate("MainWindow", "Make Bode Plot"))
        self.label_9.setText(_translate("MainWindow", "Amplitude Plot"))
        self.label_20.setText(_translate("MainWindow", "Phase plot"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _translate("MainWindow", "PE1, Practicum 4"))
        self.label.setText(_translate("MainWindow", "© Tobias Göbel & Léon van Velzen (2018)"))

from pyqtgraph import PlotWidget
